version: "2"
services:
  rabbit:
    container_name: binance-stream-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
    restart: always

  redis:
    container_name: binance-stream-redis
    image: redis
    ports:
      - "6380:6379"
    command: [
      "bash", "-c",
      '
         docker-entrypoint.sh
         --requirepass password
        '
    ]
    restart: always

  postgres:
    container_name: binance-stream-postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "binance_stream_db"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always

  listener:
    container_name: binance-stream-listener
    build:
      context: listener
    depends_on:
      - rabbit
    ports:
      - "8001:8000"
    links:
      - "rabbit:binance-stream-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  logger:
    container_name: binance-stream-logger
    build:
      context: logger
    depends_on:
      - rabbit
      - postgres
    ports:
      - "8002:8000"
    links:
      - "rabbit:binance-stream-rabbitmq"
      - "postgres:binance-stream-postgres"
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_NAME: "binance_stream_db"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    container_name: binance-stream-gateway
    build:
      context: gateway
    depends_on:
      - rabbit
    ports:
      - "8003:8000"
    links:
      - "rabbit:binance-stream-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  runner:
    container_name: binance-stream-runner
    build:
      context: runner
    depends_on:
      - rabbit
      - listener
    links:
      - "rabbit:binance-stream-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"